# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# branches to build
branches:
# whitelist
  only:
    - build

# Do not build on tags (GitHub only)
skip_tags: true


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: http://www.appveyor.com/docs/installed-software
os: Visual Studio 2015

environment:
  PROJECT_DIR: &PROJECT_DIR c:\project
  REPO_DIR:  c:\project\windows-chewing-tsf  # directory created by appveyor
  BUILD_DIR: c:\build
  INST_DIR:  c:\build\installer

  # should replaced by using chocolatey
  NSIS_DIR: c:\nsis
  NSIS_EXE: c:\nsis\Bin\makensis.exe
  NSIS_VERSION: 3.0b3
  NSIS_URL: https://prdownloads.sourceforge.net/nsis/nsis-3.0b3-setup.exe

  SQLITE_DIR: c:\sqlite
  SQLITE_INST:
  SQLITE_VERSION: 3.11.1
  SQLITE_URL: https://www.sqlite.org/2016/sqlite-amalgamation-3110100.zip

  CMAKE_GEN_X86: Visual Studio 14 2015
  CMAKE_GEN_X64: Visual Studio 14 2015 Win64

  SOL_FILE: windows-chewing-tsf.sln
  MSBUILD_CMD_X86: /m /p:Configuration=Release /t:ChewingPreferences;ChewingTextService;all_static_data;data
  MSBUILD_CMD_X64: /m /p:Configuration=Release /t:ChewingTextService

# clone directory
clone_folder: *PROJECT_DIR

# set clone depth
clone_depth: 1

matrix:
  # set this flag to immediately finish build once one of the jobs fails.
  fast_finish: true

install:
  # Setting up NSIS
  - 'cd \'
  - 'appveyor DownloadFile "%NSIS_URL%" -FileName "nsissetup.exe"'
  - '"nsissetup.exe" /S /D=%NSIS_DIR%'  # double quotes are not allowed in /D


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules
  - 'cd "%REPO_DIR%"'
  - 'git submodule update --init --remote --depth 1 --recursive'

  # updating sqlite-amalgamation
  - 'cd \'
  - 'appveyor DownloadFile "%SQLITE_URL%" -FileName "sqlite.zip"'
  - '7z e "sqlite.zip" -o"%SQLITE_DIR%"'
  - 'copy /Y "%SQLITE_DIR%\*" "%REPO_DIR%\libchewing\thirdparty\sqlite-amalgamation"'

# to run your custom scripts instead of automatic MSBuild
build_script:
  # build start
  - 'mkdir "%BUILD_DIR%"'

  # build x86
  - 'cd "%BUILD_DIR%" && mkdir "x86" && cd "x86"'
  - 'cmake -G "%CMAKE_GEN_X86%" "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD_X86%'

  # build x64
  - 'cd "%BUILD_DIR%" && mkdir "x64" && cd "x64"'
  - 'cmake -G "%CMAKE_GEN_X64%" "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD_X64%'

# scripts to run before deployment
after_build:
  # prepare for NSIS
  - 'mkdir "%INST_DIR%" && cd "%INST_DIR%"'
  - 'copy "%REPO_DIR%\installer\*" ".\"'
  - 'copy "%REPO_DIR%\COPYING.txt" ".\..\"'  # special case for LICENSE file

  - 'cd "%INST_DIR%" && mkdir "Dictionary"'
  - 'copy "%BUILD_DIR%\x86\libchewing\data\*" ".\Dictionary"'

  - 'cd "%INST_DIR%" && mkdir "x86"'
  - 'copy "%BUILD_DIR%\x86\ChewingTextService\Release\*.dll" ".\x86"'
  - 'copy "%BUILD_DIR%\x86\ChewingPreferences\Release\*.exe" "."'

  - 'cd "%INST_DIR%" && mkdir "x64"'
  - 'copy "%BUILD_DIR%\x64\ChewingTextService\Release\*.dll" ".\x64"'

  # run NSIS
  - 'cd "%INST_DIR%"'
  - '"%NSIS_EXE%" "installer.nsi"'

  # prepare for artifacts packaging
  - 'cd "%INST_DIR%"'
  - 'copy "windows-chewing-tsf.exe" "%PROJECT_DIR%"'  # the artifact must reside at the source repo root

  # generate SHA1
  - 'cd "%PROJECT_DIR%"'
  - 'powershell -Command "& { (Get-FileHash -Algorithm SHA1 "windows-chewing-tsf.exe").hash; }" > "windows-chewing-tsf.sha1"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: windows-chewing-tsf.exe
    name: installer
  - path: windows-chewing-tsf.sha1
    name: checksum
